# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])


# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.ndim, a1.dtype, type(a1)

((3,), 3, 1, dtype('int32'), numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim, a2.dtype, type(a2)

((2, 3), 6, 2, dtype('int32'), numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.ndim, a3.dtype, type(a3)

((2, 3, 3), 18, 3, dtype('int32'), numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df


0  1  2
0  1  2  3
1  4  5  6

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,size=(7,2))
random_array


array([[5, 7],
       [5, 7],
       [9, 4],
       [3, 2],
       [9, 5],
       [9, 1],
       [4, 5]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.rand(3,5)
random_array_float


array([[0.79282082, 0.5161291 , 0.65254742, 0.19336793, 0.41313427],
       [0.59627659, 0.39617025, 0.97442913, 0.27281504, 0.96702681],
       [0.12058608, 0.17410168, 0.79857227, 0.32809765, 0.95409644]])

In [19]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2 = np.random.randint(0,10, size=(4,6))
random_array_2


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_3 = np.random.randint(1,10, size=(3,7))
# Find the unique numbers in the array you just created
np.unique(random_array_3)

array([1, 2, 3, 4, 5, 7, 9])

In [26]:
# Find the 0'th index of the latest array you created
random_array_3[:1,:1], random_array_3, random_array_3[0][0]


(array([[9]]),
 array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 9)

In [27]:
# Get the first 2 rows of latest array you created
random_array_3[:2]


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [28]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_3[:2,:2]


array([[9, 1],
       [5, 3]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(0)
random_array_4 = np.random.randint(0,10, size=(3,5))
ones_1 = np.ones((3,5))
random_array_4, ones_1


(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [30]:
# Add the two arrays together
random_array_4 + ones_1

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [31]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))
ones_2


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# Try add the array of ones and the other most recent array together
random_array_4 + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [33]:
random_array_4.shape, ones_2.shape

((3, 5), (5, 3))

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [34]:
random_array_4 + ones_2.T

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [35]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3,5))
ones_3


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# Subtract the new array of ones from the other most recent array
random_array_4 - ones_3


array([[ 4., -1.,  2.,  2.,  6.],
       [ 8.,  2.,  4.,  1.,  3.],
       [ 6.,  5.,  7.,  7.,  0.]])

In [37]:
# Multiply the ones array with the latest array
random_array_4 * ones_3

array([[5., 0., 3., 3., 7.],
       [9., 3., 5., 2., 4.],
       [7., 6., 8., 8., 1.]])

In [38]:
# Take the latest array to the power of 2 using '**'
random_array_4 ** 2

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [39]:
# Do the same thing with np.square
np.square(random_array_4)


array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [40]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_4)

4.733333333333333

In [41]:
# Find the maximum of the latest array using np.max()
np.max(random_array_4)


9

In [42]:
# Find the minimum of the latest array using np.min()
np.min(random_array_4)

0

In [43]:
# Find the standard deviation of the latest array
np.std(random_array_4)

2.6449112566503166

In [44]:
# Find the variance of the latest array
np.var(random_array_4)

6.995555555555556

In [45]:
# Reshape the latest array to (3, 5, 1)
random_array_4.reshape((3,5,1))


array([[[5],
        [0],
        [3],
        [3],
        [7]],

       [[9],
        [3],
        [5],
        [2],
        [4]],

       [[7],
        [6],
        [8],
        [8],
        [1]]])

In [46]:
# Transpose the latest array
random_array_4.T


array([[5, 9, 7],
       [0, 3, 6],
       [3, 5, 8],
       [3, 2, 8],
       [7, 4, 1]])

What does the transpose do?

In [47]:
random_array_4 # exchange the rows with columns

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [52]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
random_array_5 = np.random.randint(0,10, size=(3,3))
random_array_6 = np.random.randint(0,10, size=(3,2))
random_array_5, random_array_6


(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]]),
 array([[4, 7],
        [6, 8],
        [8, 1]]))

In [54]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_5, random_array_6) # expected_size = (3,2)


array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [56]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)
random_array_7 = np.random.randint(0,10, size=(4,3))
random_array_8 = np.random.randint(0,10, size=(4,3))
random_array_7, random_array_8

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]]),
 array([[8, 8, 1],
        [6, 7, 7],
        [8, 1, 5],
        [9, 8, 9]]))

In [57]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_7, random_array_8)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [58]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_7, random_array_8.T)


array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [59]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_7.shape, random_array_8.shape


((4, 3), (4, 3))

In [60]:
# Compare the two arrays with '>'
random_array_7 > random_array_8


array([[False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [61]:
# Compare the two arrays with '>='
random_array_7 >= random_array_8


array([[False, False,  True],
       [False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [62]:
# Find which elements of the first array are greater than 7
random_array_7 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [63]:
# Which parts of each array are equal? (try using '==')
random_array_7 == random_array_8


array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [64]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_7)


array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [65]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_7)


array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [66]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_7)


5

In [67]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_7)


1

In [68]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_7, axis=1)


array([0, 2, 1, 1], dtype=int64)

In [69]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_7, axis=0)


array([1, 0, 2], dtype=int64)

In [70]:
random_array_7

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [74]:
# Create an array of normally distributed random numbers
random_numbers_9 = np.random.normal(0, 1, 10)
random_numbers_9


array([-0.22925063,  2.16171737, -0.95693143,  0.06731083,  0.20649884,
       -0.45688133, -1.05997576,  0.61495732,  1.42966077, -0.21195226])

In [79]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
print(evenly_spaced_array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

In [80]:
np.empty((2,3))

array([[6.36598738e-314, 8.48798317e-314, 1.48539705e-313],
       [1.48539705e-313, 1.90979621e-313, 1.27319747e-313]])